sudo: required
dist: trusty
language: ruby
rvm:
- 2.1
- 2.3
before_install:
- sudo apt-get -y install python-pip && sudo pip install docker-compose && docker-compose -v
- gem install --no-document -v '~> 1.12' bundler
before_script:
- bundle install
